name: finmind
description: "Track finances through bank SMS messages"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler: ^11.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_sms_inbox: ^1.0.3
  intl: ^0.18.1
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
